
services:
  #  MongoDB Database
  mongodb-school:
    image: mongo
    container_name: mongodb-school
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - devops-network

  #  MongoDB Exporter for Prometheus
  mongodb-exporter:
    image: percona/mongodb_exporter:latest
    container_name: mongodb-exporter
    restart: unless-stopped
    ports:
      - "9216:9216"
    environment:
      MONGODB_URI: "mongodb://root:example@mongodb-school:27017"
    depends_on:
      - mongodb-school
    networks:
      - devops-network

  #  .NET App (DevOpsApp)
  devopsapp:
    image: macfatty/devops-blog:latest
    container_name: devopsapp
    restart: unless-stopped
    ports:
      - "5163:5163"
    depends_on:
      - mongodb-school
    environment:
      - ASPNETCORE_URLS=http://+:5163
      - ConnectionStrings__MongoDB=mongodb://root:example@mongodb-school:27017
    networks:
      - devops-network

  #  Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - devops-network

  #  Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - devops-network

volumes:
  mongodb_data:
  grafana-data:

networks:
  devops-network:
