
services:
  mongodb-school:
    image: mongo
    container_name: mongodb-school
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - devops-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - devops-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops-network

  mongodb-exporter:
    image: percona/mongodb_exporter:0.39.0
    container_name: mongodb-exporter
    restart: unless-stopped
    command:
      - "--mongodb.uri=mongodb://mongodb-school:27017"
      - "--collect-all"  # Forces all available metrics to be collected
    ports:
      - "9216:9216"
    networks:
      - devops-network

volumes:
  mongodb_data:
  grafana_data:
  prometheus_data:

networks:
  devops-network:
